trigger:
  batch: true
  branches:
    include:
      - "master"

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.0
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.4
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master    

variables:
- group: Release Management Resources
- group: RELEASE das-tools-servicebus-support

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  pool:
    name: DAS - Continuous Deployment Agents
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-tools-servicebus-support
  jobs:
  - template: azure-pipelines-templates/deploy/job/arm-deploy.yml@das-platform-building-blocks
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/azure/template.parameters.json
      ConfigSchemaPath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-tools-servicebus-support
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)
        AzureAdConfigurationClientSecret: $(AzureAdConfigurationClientSecret)
        NServiceBusLicense: $(NServiceBusLicense)
        RedisConnectionString: $(DefaultSessionRedisConnectionString)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/SFA.DAS.Tools.Servicebus.Support.Web.zip
  - template: pipeline-templates/job/function-deploy.yml
    parameters:
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/SFA.DAS.Tools.Servicebus.Support.Functions.zip

- stage: Deploy_PP
  dependsOn: Build
  displayName: Deploy to PP
  pool:
    name: DAS - Continuous Deployment Agents
  variables:
  - group: PreProd Management Resources
  - group: PreProd Shared Resources
  - group: PREPROD das-tools-servicebus-support
  jobs:
  - template: azure-pipelines-templates/deploy/job/arm-deploy.yml@das-platform-building-blocks
    parameters:
      ServiceConnection: SFA-DIG-PreProd-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: PP
      TemplatePath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/azure/template.parameters.json
      ConfigSchemaPath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-tools-servicebus-support
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)
        AzureAdConfigurationClientSecret: $(AzureAdConfigurationClientSecret)
        NServiceBusLicense: $(NServiceBusLicense)
        RedisConnectionString: $(DefaultSessionRedisConnectionString)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: PP
      ServiceConnection: SFA-DIG-PreProd-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/SFA.DAS.Tools.Servicebus.Support.Web.zip
  - template: pipeline-templates/job/function-deploy.yml
    parameters:
      DeploymentApprovals: PP
      ServiceConnection: SFA-DIG-PreProd-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/SFA.DAS.Tools.Servicebus.Support.Functions.zip

- stage: Deploy_PROD
  dependsOn: Build
  displayName: Deploy to PROD
  pool:
    name: DAS - Continuous Deployment Agents
  variables:
  - group: Prod Management Resources
  - group: Prod Shared Resources
  - group: PROD das-tools-servicebus-support
  jobs:
  - template: azure-pipelines-templates/deploy/job/arm-deploy.yml@das-platform-building-blocks
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: PROD
      TemplatePath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/azure/template.parameters.json
      ConfigSchemaPath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-tools-servicebus-support
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)
        AzureAdConfigurationClientSecret: $(AzureAdConfigurationClientSecret)
        NServiceBusLicense: $(NServiceBusLicense)
        RedisConnectionString: $(DefaultSessionRedisConnectionString)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: PROD
      ServiceConnection: SFA-DIG-Prod-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/SFA.DAS.Tools.Servicebus.Support.Web.zip
  - template: pipeline-templates/job/function-deploy.yml
    parameters:
      DeploymentApprovals: PROD
      ServiceConnection: SFA-DIG-Prod-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsServiceBusSupportArtifacts/SFA.DAS.Tools.Servicebus.Support.Functions.zip
