trigger:
  batch: true
  branches:
    include:
      - "master"

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/DASD-12052
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.8
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master    

variables:
- name: SolutionBaseName
  value: SFA.DAS.Tools.Servicebus.Support
- name: BuildConfiguration
  value: release
- group: Release Management Resources
- group: RELEASE das-tools-servicebus-support

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  pool:
    name: DAS - Continuous Deployment Agents
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-tools-servicebus-support
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: Deploy_PP
  dependsOn: Build
  displayName: Deploy to PP
  pool:
    name: DAS - Continuous Deployment Agents
  variables:
  - group: PreProd Management Resources
  - group: PreProd Shared Resources
  - group: PREPROD das-tools-servicebus-support
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: PP
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DIG-PreProd-ARM

- stage: Deploy_PROD
  dependsOn: Build
  displayName: Deploy to PROD
  pool:
    name: DAS - Continuous Deployment Agents
  variables:
  - group: Prod Management Resources
  - group: Prod Shared Resources
  - group: PROD das-tools-servicebus-support
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: PROD
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DIG-Prod-ARM
