pool:
  name: DAS - Continuous Integration Agents

pr: 
  paths:
    include:
      - manifests/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile

resources:
  repositories:
    - repository: self
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/tags/0.4.12
      endpoint: SkillsFundingAgency

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - manifests/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile

variables:
- group: Release Management Resources
- name: ContainerImageName
  value: das-tools-servicebus-support
- name: buildConfiguration
  value: 'release'

stages:
- stage: build_image
  displayName: Build Image
  jobs:
  - job: build_image
    displayName: Build Image
    steps:
    - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

    - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
      parameters:
        ContainerRegistryName: $(PublicAcrName)
        ServiceConnection: SFA-DIG-Prod-ARM
        ImageName: $(ContainerImageName)
        BranchToCreateLatestTag: master
        
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        contents: |
          azure/**
          manifests/**
        targetFolder: '$(build.artifactstagingdirectory)/publish'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathtoPublish: '$(build.artifactstagingdirectory)/publish'

- stage: Build_function
  displayName: Build function
  jobs:
  - job: build_function
    steps:
      - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: 'src/SFA.DAS.Tools.Servicebus.Support.Functions/SFA.DAS.Tools.Servicebus.Support.Functions.csproj'
          noCache: true

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: 'src/SFA.DAS.Tools.Servicebus.Support.Functions/SFA.DAS.Tools.Servicebus.Support.Functions.csproj'
          arguments: '--configuration $(buildConfiguration) --no-restore'

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: '**/*.UnitTests.csproj'
          arguments: '--configuration $(buildConfiguration) --no-build'

      - task: DotNetCoreCLI@2
        displayName: 'Publish Work Function App'
        inputs:
          command: publish
          publishWebProjects: false
          projects: 'src/SFA.DAS.Tools.Servicebus.Support.Functions/SFA.DAS.Tools.Servicebus.Support.Functions.csproj'
          arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          pathtoPublish: '$(build.artifactstagingdirectory)/publish'
