<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\ServiceBus\AsbService_BACKUP_1713.cs" />
    <Compile Remove="Services\ServiceBus\AsbService_BASE_1713.cs" />
    <Compile Remove="Services\ServiceBus\AsbService_LOCAL_1713.cs" />
    <Compile Remove="Services\ServiceBus\AsbService_REMOTE_1713.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.3.11" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.61.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Polly" Version="8.7.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
    <PackageReference Include="System.Text.Json" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.Tools.Servicebus.Support.Core\SFA.DAS.Tools.Servicebus.Support.Domain.csproj" />
  </ItemGroup>

</Project>
